server:
  port: 8080
  # 设定最大的上传文件大小
  request:
    maxFileSize: 2048mb

solon.app:
  name: 'fast-fs'
  group: 'fs'

# 日志配置
solon.logging.appender:
  console:
    level: DEBUG

# sqltoy 数据源
datasource:
  driver-class-name: org.postgresql.Driver
  username: xlz
  password: xlz342601
  jdbcUrl: jdbc:postgresql://101.43.65.9:5432/fastfs?useSSL=false&useUnicode=true&characterEncoding=UTF-8



# 文件服务器配置
fs:
  dir: D:\EasyFs
  uuidName: true
  useSm: true
  useNginx: false
  nginxUrl: http://localhost:80/
  master: true
  works:
    - 172.31.227.99:8081
#    - 106.13.1.173:41198
  node:
    nodeName: master
    total: 20G


# admin账户配置
admin.uname: admin
admin.pwd: 123

# 域名配置
domain: http://localhost:${server.port}

# sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: fastfs
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true